server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: --
          clone-on-start: true
          basedir: .config-git-remote

  security:
    user:
      name: --
      password: --
