spring:
  profiles:
    active: local

logging:
  level:
    root: warn #debug, trace, warn, error, etc
    dev.park.jpa: info
custom:
  property:
    single: custom-property
    comlist: comma,sparated,list,to,value
    ncp:
      id: api-id
      key: api-key
      url: http://ncp.com/
# custom
---
spring:
  profiles:
    active:
      on-profiles: docker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/demo_jpa_schema
    username: demo_jpa
    password: Qkrwngud12@
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
---
spring:
  profiles:
    active:
      on-profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo_jpa_schema
    username: demo_jpa
    password: Qkrwngud12@
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
---
spring:
  profiles:
    active:
      on-profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo_jpa_schema
    username: demo_jpa
    password: Qkrwngud12@
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

custom:
  property:
    single: test-property
